//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPrivilegeControlLangPack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FunctionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolPrivilegeControlLangPack.FunctionRes", typeof(FunctionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Management.
        /// </summary>
        public static string AccessManage {
            get {
                return ResourceManager.GetString("AccessManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Audit Log Management.
        /// </summary>
        public static string AuditLogManage {
            get {
                return ResourceManager.GetString("AuditLogManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Audit Log Data.
        /// </summary>
        public static string AuditLogManage_Export {
            get {
                return ResourceManager.GetString("AuditLogManage_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized History Management.
        /// </summary>
        public static string AuthorizedHistoryManage {
            get {
                return ResourceManager.GetString("AuthorizedHistoryManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Management.
        /// </summary>
        public static string FManage {
            get {
                return ResourceManager.GetString("FManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Function.
        /// </summary>
        public static string FManage_Create {
            get {
                return ResourceManager.GetString("FManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Function.
        /// </summary>
        public static string FManage_Delete {
            get {
                return ResourceManager.GetString("FManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Function.
        /// </summary>
        public static string FManage_Edit {
            get {
                return ResourceManager.GetString("FManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function Type Management.
        /// </summary>
        public static string FTManage {
            get {
                return ResourceManager.GetString("FTManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Function Type.
        /// </summary>
        public static string FTManage_Create {
            get {
                return ResourceManager.GetString("FTManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Function Type.
        /// </summary>
        public static string FTManage_Delete {
            get {
                return ResourceManager.GetString("FTManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Function Type.
        /// </summary>
        public static string FTManage_Edit {
            get {
                return ResourceManager.GetString("FTManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Login_Reset {
            get {
                return ResourceManager.GetString("Login_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login User Management.
        /// </summary>
        public static string LoginUserManage {
            get {
                return ResourceManager.GetString("LoginUserManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Login User.
        /// </summary>
        public static string LoginUserManage_Create {
            get {
                return ResourceManager.GetString("LoginUserManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Login User.
        /// </summary>
        public static string LoginUserManage_Delete {
            get {
                return ResourceManager.GetString("LoginUserManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Login User.
        /// </summary>
        public static string LoginUserManage_Edit {
            get {
                return ResourceManager.GetString("LoginUserManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Management.
        /// </summary>
        public static string LUOrganizationManage {
            get {
                return ResourceManager.GetString("LUOrganizationManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization.
        /// </summary>
        public static string LUOrganizationManage_Create {
            get {
                return ResourceManager.GetString("LUOrganizationManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organization.
        /// </summary>
        public static string LUOrganizationManage_Delete {
            get {
                return ResourceManager.GetString("LUOrganizationManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization.
        /// </summary>
        public static string LUOrganizationManage_Edit {
            get {
                return ResourceManager.GetString("LUOrganizationManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Details Management.
        /// </summary>
        public static string LUOrgDetailsManage {
            get {
                return ResourceManager.GetString("LUOrgDetailsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Organization Details.
        /// </summary>
        public static string LUOrgDetailsManage_Create {
            get {
                return ResourceManager.GetString("LUOrgDetailsManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Organization Details.
        /// </summary>
        public static string LUOrgDetailsManage_Delete {
            get {
                return ResourceManager.GetString("LUOrgDetailsManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Organization Details.
        /// </summary>
        public static string LUOrgDetailsManage_Edit {
            get {
                return ResourceManager.GetString("LUOrgDetailsManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Management.
        /// </summary>
        public static string LURoleManage {
            get {
                return ResourceManager.GetString("LURoleManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User Role.
        /// </summary>
        public static string LURoleManage_Create {
            get {
                return ResourceManager.GetString("LURoleManage_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User Role.
        /// </summary>
        public static string LURoleManage_Delete {
            get {
                return ResourceManager.GetString("LURoleManage_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Role.
        /// </summary>
        public static string LURoleManage_Edit {
            get {
                return ResourceManager.GetString("LURoleManage_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info Management.
        /// </summary>
        public static string SystemInfoManage {
            get {
                return ResourceManager.GetString("SystemInfoManage", resourceCulture);
            }
        }
    }
}
