//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPrivilegeControlLangPack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MsgRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolPrivilegeControlLangPack.MsgRes", typeof(MsgRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property: {0} Error: {1}.
        /// </summary>
        public static string E000 {
            get {
                return ResourceManager.GetString("E000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required!.
        /// </summary>
        public static string E001 {
            get {
                return ResourceManager.GetString("E001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} exists..
        /// </summary>
        public static string E002 {
            get {
                return ResourceManager.GetString("E002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record does not exist..
        /// </summary>
        public static string E003 {
            get {
                return ResourceManager.GetString("E003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record may modified by other process!.
        /// </summary>
        public static string E004 {
            get {
                return ResourceManager.GetString("E004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed!.
        /// </summary>
        public static string E005 {
            get {
                return ResourceManager.GetString("E005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Failed!.
        /// </summary>
        public static string E006 {
            get {
                return ResourceManager.GetString("E006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match the {1}.
        /// </summary>
        public static string E007 {
            get {
                return ResourceManager.GetString("E007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect {0} or {1}. Please try again..
        /// </summary>
        public static string E008 {
            get {
                return ResourceManager.GetString("E008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inactive, please contact your administrator..
        /// </summary>
        public static string E009 {
            get {
                return ResourceManager.GetString("E009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record had been deleted!.
        /// </summary>
        public static string E010 {
            get {
                return ResourceManager.GetString("E010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Timeout! Could not find the Authorized Info..
        /// </summary>
        public static string E011 {
            get {
                return ResourceManager.GetString("E011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect {0}. Please try again..
        /// </summary>
        public static string E012 {
            get {
                return ResourceManager.GetString("E012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s length must be {1} or {2}!.
        /// </summary>
        public static string E013 {
            get {
                return ResourceManager.GetString("E013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain both upper case and lower case..
        /// </summary>
        public static string E014 {
            get {
                return ResourceManager.GetString("E014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should contain at least one symbol..
        /// </summary>
        public static string E015 {
            get {
                return ResourceManager.GetString("E015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain one or more numerical digits.
        /// </summary>
        public static string E016 {
            get {
                return ResourceManager.GetString("E016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password should not be the same with previous {0} used password records..
        /// </summary>
        public static string E017 {
            get {
                return ResourceManager.GetString("E017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of Login attempts exceeded. &lt;br/&gt;Your account has been Suspended! Please contact your system administrator..
        /// </summary>
        public static string E018 {
            get {
                return ResourceManager.GetString("E018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record Found!.
        /// </summary>
        public static string E019 {
            get {
                return ResourceManager.GetString("E019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s must integer and its length must be {1} or the multiple of {1}..
        /// </summary>
        public static string E020 {
            get {
                return ResourceManager.GetString("E020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account have been locked..
        /// </summary>
        public static string E021 {
            get {
                return ResourceManager.GetString("E021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function has been locked!.
        /// </summary>
        public static string E022 {
            get {
                return ResourceManager.GetString("E022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update or delete {0}, Since it has sub-{0}..
        /// </summary>
        public static string E023 {
            get {
                return ResourceManager.GetString("E023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot contain space or special character..
        /// </summary>
        public static string E024 {
            get {
                return ResourceManager.GetString("E024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You might not have permission on this operation..
        /// </summary>
        public static string E025 {
            get {
                return ResourceManager.GetString("E025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or edit specific function without function type..
        /// </summary>
        public static string E026 {
            get {
                return ResourceManager.GetString("E026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2} characters..
        /// </summary>
        public static string E027 {
            get {
                return ResourceManager.GetString("E027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot excess {1} records..
        /// </summary>
        public static string E028 {
            get {
                return ResourceManager.GetString("E028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add or edit specific {0} without {1}..
        /// </summary>
        public static string E029 {
            get {
                return ResourceManager.GetString("E029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one option..
        /// </summary>
        public static string E030 {
            get {
                return ResourceManager.GetString("E030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one {0}..
        /// </summary>
        public static string E031 {
            get {
                return ResourceManager.GetString("E031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select {0}..
        /// </summary>
        public static string E032 {
            get {
                return ResourceManager.GetString("E032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successfully!.
        /// </summary>
        public static string I000 {
            get {
                return ResourceManager.GetString("I000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Successfully!.
        /// </summary>
        public static string I001 {
            get {
                return ResourceManager.GetString("I001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Warning!&lt;/strong&gt; Any changes of Function Type will affact the execution time..
        /// </summary>
        public static string I002 {
            get {
                return ResourceManager.GetString("I002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out.
        /// </summary>
        public static string I003 {
            get {
                return ResourceManager.GetString("I003", resourceCulture);
            }
        }
    }
}
