//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolPrivilegeControlLangPack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SampleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoolPrivilegeControlLangPack.SampleResource", typeof(SampleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Module.
        /// </summary>
        public static string AttendanceModule {
            get {
                return ResourceManager.GetString("AttendanceModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Executive Officer.
        /// </summary>
        public static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Privilege Control System Part 1 -- asp.net MVC.
        /// </summary>
        public static string Home_IndexPart1 {
            get {
                return ResourceManager.GetString("Home_IndexPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Privilege Control System Part 2 -- asp.net MVC with WCF.
        /// </summary>
        public static string Home_IndexPart2 {
            get {
                return ResourceManager.GetString("Home_IndexPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool Privilege Control System Part 3 -- Angular Single-Page Application.
        /// </summary>
        public static string Home_IndexPart3 {
            get {
                return ResourceManager.GetString("Home_IndexPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HR Module.
        /// </summary>
        public static string HRModule {
            get {
                return ResourceManager.GetString("HRModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Module.
        /// </summary>
        public static string LeaveModule {
            get {
                return ResourceManager.GetString("LeaveModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Salary Info.
        /// </summary>
        public static string MaintainSalaryInfo {
            get {
                return ResourceManager.GetString("MaintainSalaryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Team.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Team Officer.
        /// </summary>
        public static string PTO {
            get {
                return ResourceManager.GetString("PTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Team Programmer.
        /// </summary>
        public static string PTP {
            get {
                return ResourceManager.GetString("PTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Info Management.
        /// </summary>
        public static string SalaryInfoManagement {
            get {
                return ResourceManager.GetString("SalaryInfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary Review.
        /// </summary>
        public static string SalaryReview {
            get {
                return ResourceManager.GetString("SalaryReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team.
        /// </summary>
        public static string ST {
            get {
                return ResourceManager.GetString("ST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Info Management.
        /// </summary>
        public static string StaffInfoManage {
            get {
                return ResourceManager.GetString("StaffInfoManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Sales.
        /// </summary>
        public static string STS {
            get {
                return ResourceManager.GetString("STS", resourceCulture);
            }
        }
    }
}
